Repository NOW-SOPT-CDSP-8/Spotify-BE, pull requests merged in 2024-05, with the labels that each got.

#6 [feat] 커스텀 예외클래스 생성
  spotify-web/src/main/java/com/example/spotifyweb/global/common/exception/BusinessException.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/exception/GlobalExceptionHandler.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/exception/NotFoundException.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/response/ErrorMessage.java
Labels: feat, 혁진

#8 ✨[feat] 스테이션 제목 전체조회 API 생성 #7
  spotify-web/src/main/java/com/example/spotifyweb/global/common/response/SuccessMessage.java
  spotify-web/src/main/java/com/example/spotifyweb/station/controller/StationController.java
  spotify-web/src/main/java/com/example/spotifyweb/station/dto/StationGetResponseDto.java
  spotify-web/src/main/java/com/example/spotifyweb/station/repository/StationsRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/station/service/StationService.java
Labels: feat, 혁진

#10 [feat] 스테이션에 따른 노래 목록 조회 API 생성
  spotify-web/src/main/java/com/example/spotifyweb/global/common/exception/GlobalExceptionHandler.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/response/ErrorMessage.java
  spotify-web/src/main/java/com/example/spotifyweb/music/dto/MusicGetResponseDto.java
  spotify-web/src/main/java/com/example/spotifyweb/stationMusic/StationMusicController.java
  spotify-web/src/main/java/com/example/spotifyweb/stationMusic/StationMusicRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/stationMusic/StationMusicService.java
Labels: feat, 혁진

#12 [feat] 스테이션 좋아요 api 구현
  spotify-web/src/main/java/com/example/spotifyweb/global/common/exception/GlobalExceptionHandler.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/response/ErrorMessage.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/response/SuccessMessage.java
  spotify-web/src/main/java/com/example/spotifyweb/member/repository/MemberRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/station/controller/StationController.java
  spotify-web/src/main/java/com/example/spotifyweb/station/domain/StationLiking.java
  spotify-web/src/main/java/com/example/spotifyweb/station/repository/StationLikingRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/station/repository/StationRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/station/repository/StationsRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/station/service/StationService.java
  spotify-web/src/main/java/com/example/spotifyweb/stationMusic/StationMusicService.java
Labels: feat, 보람

#16 [feat] 멤버 프로필 조회 API 생성 #14
  spotify-web/src/main/java/com/example/spotifyweb/api/card/dto/CardGetResponsedDto.java
  spotify-web/src/main/java/com/example/spotifyweb/api/member/controller/MemberController.java
  spotify-web/src/main/java/com/example/spotifyweb/api/member/dto/ProfileGetResponsedDto.java
  spotify-web/src/main/java/com/example/spotifyweb/api/member/service/MemberService.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/response/SuccessMessage.java
Labels: feat, 혁진

#17 [feat] 장르에 따른 음악 필터링 조회 API 구현
  spotify-web/src/main/java/com/example/spotifyweb/api/filter/filterRepository/FilterRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/api/music/GenreCategory.java
  spotify-web/src/main/java/com/example/spotifyweb/api/music/controller/musicController.java
  spotify-web/src/main/java/com/example/spotifyweb/api/music/domain/GenreCategory.java
  spotify-web/src/main/java/com/example/spotifyweb/api/music/domain/Music.java
  spotify-web/src/main/java/com/example/spotifyweb/api/music/dto/MusicInfo.java
  spotify-web/src/main/java/com/example/spotifyweb/api/music/dto/MusicsGetResponseDto.java
  spotify-web/src/main/java/com/example/spotifyweb/api/music/repository/MusicRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/api/music/service/MusicService.java
  spotify-web/src/main/java/com/example/spotifyweb/api/playlist/domain/Playlist.java
  spotify-web/src/main/java/com/example/spotifyweb/api/playlist/dto/PlaylistInfo.java
  spotify-web/src/main/java/com/example/spotifyweb/api/playlist/repository/PlaylistRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/response/ErrorMessage.java
  spotify-web/src/main/java/com/example/spotifyweb/global/common/response/SuccessMessage.java
Labels: feat, 보람

#21 [fix] cors 에러 해결 #20
  spotify-web/src/main/java/com/example/spotifyweb/global/config/WebConfig.java
Labels: fix, 혁진

#19 [fix] 스테이션에 따른 노래 목록 조회 API 수정 #18
  spotify-web/src/main/java/com/example/spotifyweb/api/stationMusic/StationMusicRepository.java
  spotify-web/src/main/java/com/example/spotifyweb/api/stationMusic/StationMusicService.java
Labels: fix, 혁진
